# Trace Simple Image Classifier

Task: trace and explain the dimensionality of each tensor in a simple image classifier.

## Setup

In [86]:
from fastai.vision.all import *
from fastbook import *

matplotlib.rc('image', cmap='Greys')

Get some example digits from the MNIST dataset.

In [87]:
path = untar_data(URLs.MNIST_SAMPLE)

In [88]:
threes = (path/'train'/'3').ls().sorted()
sevens = (path/'train'/'7').ls().sorted()
len(threes), len(sevens)

(6131, 6265)

Here is one image:

In [89]:
example_3 = Image.open(threes[1])
example_3

To prepare to use it as input to a neural net, we first convert integers from 0 to 255 into floating point numbers between 0 and 1.

In [90]:
example_3_tensor = tensor(example_3).float() / 255
example_3_tensor.shape

torch.Size([28, 28])

In [91]:
height, width = example_3_tensor.shape

Our particular network will ignore the spatial relationship between the features; later we'll learn about network architectures that do pay attention to spatial neighbors. So we'll *flatten* the image tensor into 28\*28 values.

In [92]:
example_3_flat = example_3_tensor.view(width * height)
example_3_flat.shape

torch.Size([784])

## Task



We'll define a simple neural network (in the book, a 3-vs-7 classifier) as the sequential combination of 3 layers. First we define each layer:

In [100]:
# Define the layers. This is where you'll try changing constants.
linear_1 = nn.Linear(in_features=784, out_features=30)
relu_layer = nn.ReLU()
linear_2 = nn.Linear(in_features=30, out_features=2)

Then we put them together in sequence.

In [101]:
simple_net = nn.Sequential(
    linear_1,
    relu_layer,
    linear_2
)

Each of `nn.Linear`, `nn.ReLU`, and `nn.Squential` are PyTorch *modules*. We can *call* a module with some input data to get the output data:

In [102]:
simple_net(example_3_flat)

tensor([ 0.1431, -0.0903], grad_fn=<AddBackward0>)

Your turn:

1. Obtain the same result as the line above by applying each layer in sequence.

The outputs of each layer are called *activations*, so we can name the variables `act1` for the activations of layer 1, and so forth.

In [103]:
inp = example_3_flat
act1 = linear_1(inp)

In [104]:
act2 = relu_layer(inp)

In [105]:
act3 = linear_2(inp)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x784 and 30x2)

2. Evaluate `act1`, `act2`, and `act3`. (Code already provided; look at the results.)

In [106]:
act1

tensor([-0.1450,  0.3325,  0.1504,  0.1666,  0.1396, -0.0020,  0.1376,  0.0232,  0.0516,  0.0704,  0.1493,  0.0732,  0.1236,  0.1597, -0.0379,  0.1472, -0.4139, -0.2662, -0.1332,  0.2307, -0.1380,
        -0.1082, -0.2397, -0.2131, -0.0058,  0.1459, -0.0050, -0.2996, -0.0855, -0.2277], grad_fn=<AddBackward0>)

In [107]:
act2

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,


In [108]:
act3

Linear(in_features=30, out_features=1, bias=True)

2. Evaluate the `shape` of `act1`, `act2`, and `act3`.

In [109]:
act1.shape
act2.shape
act3.shape

AttributeError: 'Linear' object has no attribute 'shape'

3. Write expressions for the shapes of each activation in terms of `linear_1.in_features`, `linear_2.out_features`, etc. (ignore the `torch.Size(` part)

In [56]:
act1_shape = linear_1.in_features
act2_shape = relu_layer
act3_shape = linear_2.out_features

4. Evaluate the `shape` of `linear_1.weight`, `linear_1.bias`, and the same for `linear_2`. Write expressions that give the value of each shape in terms of the `in_features` and other parameters.

In [58]:
linear_1_weight_shape = act1.weight.shape
linear_1_bias_shape = act1.bias.shape
linear_2_weight_shape = act3.weight.shape
linear_2_bias_shape = act3.bias.shape

## Analysis

1. Try changing each of the constants provided to the `nn.Linear` modules. Identify an example of:
  1. A constant that can be freely changed in the neural net definition. 
  2. A constant that cannot be changed because it depends on the input. 
  3. A pair of constants that must be changed together. 

   A. The out_feature of linear_2.  
   B. The in_feature of linear_1.  
   C. The out_feature of linear_1 and the in_feature of linear_2.  

2. Describe the relationship between the values in  `act1` and `act2`.

act2 changes the negative values in act1 with zero.